services:
  connector-torexitnodes:
    image: torexitnodes:latest
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_API_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_DURATION_PERIOD=${CONNECTOR_DURATION_PERIOD}
      - OPENCTI_BROKER_HOST=${OPENCTI_HOSTNAME}
      - OPENCTI_BROKER_PORT=${RABBITMQ_PORT}
      - OPENCTI_BROKER_USERNAME=${RABBITMQ_DEFAULT_USER}
      - OPENCTI_BROKER_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - TOR_BASE_URL=${TOR_BASE_URL}
      - TOR_BASE_API_KEY=${TOR_BASE_API_KEY}
    networks:
      - opencti-network
    restart: no

networks:
  opencti-network:
    external: true
