services:
  connector-import-catalog-data:
    image: importcatalogdata:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_API_TOKEN}
      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_DURATION_PERIOD=${CONNECTOR_DURATION_PERIOD} # ISO8601 format in String, start with 'P...' for Period

      # Connector's custom execution parameters
      - CONNECTOR_TEMPLATE_API_BASE_URL=${CONNECTOR_TEMPLATE_API_BASE_URL}
      - CONNECTOR_TEMPLATE_API_KEY=${CONNECTOR_TEMPLATE_API_KEY}
      - CONNECTOR_TEMPLATE_TLP_LEVEL=${CONNECTOR_TLP_LEVEL} # available values are: clear, white, green, amber, amber+strict, red - Default: 'clear'
      - MONGO_CONN_STR=${MONGO_CONN_STR}
      - SCOPE_NAMESPACE=${SCOPE_NAMESPACE}
      - ENDPOINT_NAMESPACE=${ENDPOINT_NAMESPACE}
    networks:
      - opencti-network

    restart: always
networks:
  opencti-network:
    external: true
