services:
  connector-template:
    image: ipregistry:latest
    volumes:
      - ./data:/data
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_API_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - INDICATOR_NAMESPACE=${INDICATOR_NAMESPACE}
      - AUTO_ENRICH=${AUTO_ENRICH}
      - IPREGISTRY_API_KEY=${IPREGISTRY_API_KEY}
      - MAX_TLP=${MAX_TLP}
      - TTL=${TTL}
      - IS_ABUSER_SCORE=${ABUSER_SCORE}
      - IS_ANONYMOUS_SCORE=${IS_ANONYMOUS_SCORE}
      - IS_ATTACKER_SCORE=${IS_ATTACKER_SCORE}
      - IS_BOGON_SCORE=${IS_BOGON_SCORE}
      - IS_CLOUD_PROVIDER_SCORE=${IS_CLOUD_PROVIDER_SCORE}
      - IS_PROXY_SCORE=${IS_PROXY_SCORE}
      - IS_RELAY_SCORE=${IS_RELAY_SCORE}
      - IS_THREAT_SCORE=${IS_THREAT_SCORE}
      - IS_TOR_SCORE=${IS_TOR_SCORE}
      - IS_TOR_EXIT_NODE_SCORE=${IS_TOR_EXIT_NODE_SCORE}
      - IS_VPN_SCORE=${IS_VPN_SCORE}
      - SUSPICIOUS_SCORE=${SUSPICIOUS_SCORE}
      - MALICIOUS_SCORE=${MALICIOUS_SCORE}
      - APPLY_SCORE_TO_OBSERVABLE=${APPLY_SCORE_TO_OBSERVABLE}
      - BATCH_SIZE=${BATCH_SIZE}

    restart: always
    networks:
      - opencti-network

networks:
  opencti-network:
    external: true
