services:
  connector-apptableimport:
    image: apptableimport:latest
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_API_TOKEN}
      - CONNECTOR_TEMPLATE_TLP_LEVEL=${CONNECTOR_TEMPLATE_TLP_LEVEL}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_DURATION_PERIOD=${CONNECTOR_DURATION_PERIOD}
      - CONNECTOR_UUID_NAMESPACE=${CONNECTOR_UUID_NAMESPACE}
      - CONNECTOR_PG_CONN_STR=${CONNECTOR_PG_CONN_STR}
      - CONNECTOR_ONLY_UNASSIGNED=${CONNECTOR_ONLY_UNASSIGNED}
      - CONNECTOR_OVERWRITE_EXISTING=${CONNECTOR_OVERWRITE_EXISTING}
      - CONNECTOR_INITIAL_LAST_RUN=${CONNECTOR_INITIAL_LAST_RUN}
    volumes:
      - ./data:/data
    restart: always
    networks:
      - opencti-network

networks:
  opencti-network:
    external: true
