version: '3'
services:
  connector-abuseipdb:
    image: opencti/connector-abuseipdb:rolling
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
    networks:
      - opencti-network
    restart: always

networks:
  opencti-network:
    external: true